In [2]:
import numpy as np

d=np.arange(6)
print(d, d.shape)

[0 1 2 3 4 5] (6,)


In [3]:
# 1차원 배열의 인덱싱
print(d[0], d[1], d[2], d[-1], d[-2])

0 1 2 5 4


In [4]:
# 1차원 배열의 슬라이싱
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])
d[0]=10 # 요소 값 변경
print(d)

[2] [0 1 2 3 4 5] [0 1 2 3 4]
[0 2 4] [5 4 3 2 1 0]
[10  1  2  3  4  5]


In [5]:
d=np.arange(12).reshape(3, 4)
print(d, d.shape) #안맞아떨어지는걸로 하면 오류발생

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [7]:
# 2차원 배열의 슬라이싱
print(d[0]) # 0행만 슬라이싱
print(d[0,:]) # 0행의 전체 열 슬라이싱
print(d[:,:-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d[::2,::2]) # 2행 2열 간격으로 전체 행과 열 슬라이싱

[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]


In [8]:
d[0]=20 # 0번 행 요소를 모두 20으로 변경
print(d)

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
print(d>2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [11]:
print(d[d>2])

[20 20 20 20  4  5  6  7  8  9 10 11]


In [12]:
print(d[True])
print(d[False]) #기본적으로 True 속성을 갖고 있음

[[[20 20 20 20]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[]
