<a href="https://colab.research.google.com/github/Tiabet/Python_Study/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [8]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
type(arr2)

numpy.ndarray

In [11]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr2[1,3]

8