In [1]:
import torch

In [2]:
list_of_tensors = [torch.rand(2, 2) for _ in range(5)]

In [6]:
list_of_tensors

[tensor([[0.2904, 0.4155],
         [0.6132, 0.2069]]),
 tensor([[0.5898, 0.9801],
         [0.4778, 0.5516]]),
 tensor([[0.2492, 0.5798],
         [0.6602, 0.9692]]),
 tensor([[0.1025, 0.5955],
         [0.2872, 0.6207]]),
 tensor([[0.1480, 0.4658],
         [0.3018, 0.1729]])]

In [19]:

# Creating a 2D tensor
tensor_2d = torch.tensor([[[1, 2]]])
tensor_2d_tensor = torch.tensor([tensor_2d])

TypeError: only integer tensors of a single element can be converted to an index

In [20]:
tensor_2d_tensor

tensor([[1, 2],
        [3, 4]])

In [21]:
tensor_2d

tensor([[[1, 2]]])